# Generated by Django 2.0.8 on 2018-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dingdang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(max_length=255, null=True)),
                ('Pid', models.CharField(max_length=255, null=True)),
                ('count', models.CharField(max_length=255, null=True)),
                ('buyname', models.CharField(max_length=255, null=True)),
                ('beizhu', models.CharField(max_length=255, null=True)),
                ('sengdforname', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('tbID', models.CharField(max_length=255, null=True)),
                ('wuliu', models.CharField(max_length=255, null=True)),
                ('wlID', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('key', models.CharField(max_length=255, null=True)),
                ('imgurl', models.EmailField(max_length=255, null=True)),
                ('imgurl0', models.EmailField(max_length=255, null=True)),
                ('imgurl1', models.EmailField(max_length=255, null=True)),
                ('imgurl2', models.EmailField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('price0', models.CharField(max_length=255, null=True)),
                ('count', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('beizhu', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
